### ISSUE TITLE
Polymer.mixin2

### ISSUE THREAD

**Issue by djrm** [Polymer/vulcanize#136]
It seems that mixin2 isn't a Polymer method anymore, removing the lines that include Polymer.mixin2 fixes the issue, but im not sure if the removal produces side effects.

**Comment by djrm** [comment]
by the way im using vulcanize 0.7.9 and the latest polymer

**Comment by azakus** [comment]
`mixin2` is not part of polymer, but something `core-focusable` adds to enable a certain mixin setup required by a few elements.

Which elements are you including that you see this error?

**Comment by Goblinlordx** [comment]
I am running into the same issue.  Pre-vulcanized it is fine.  After vulcanize, I receive:

TypeError: Polymer.mixin is not a function
TypeError: document._currentScript is undefined
ReferenceError: Platform is not defined
TypeError: document.registerElement is not a function
TypeError: element.init is not a function
ReferenceError: CustomElements is not defined

**Comment by djrm** [comment]
it was my fault, i had an unfinished import tag, something like <link rel="import"

**Comment by KrisSiegel** [comment]
While I know the OP's issue was resolved due to an unfinished import tag however I'm experiencing the same issue when including paper-button. Ultimately the vulcanized stuff fails unless I explicitly include scripts from within the paper-button-base object itself at the top of my html file.

```
<link rel="import" href="ext-lib/polymer/polymer.html">
<script src="ext-lib/core-focusable/polymer-mixin.js"></script>
<script src="ext-lib/core-focusable/core-focusable.js"></script>
```

I'm also getting a few other errors related to the usage of 'this' inside of other paper elements but I think that's a separate issue.

**Comment by rsORAU** [comment]
@KrisSiegel did you ever find a solution to your issue? I have a similar issue with paper-icon-button and iron-icons.

**Comment by KrisSiegel** [comment]
@rsORAU unfortunately no. Ultimately I moved away from Polymer because of it's immaturity and weight. I would assume it's much better by now but I haven't touched it in over a year at this point. Sorry.
