### ISSUE TITLE
Ignoring duplicate element definition: undefined

### ISSUE THREAD

**Issue by MetaMemoryT** [Polymer/vulcanize#164]
latest vulcanize + hydrolysis from git

getting a bunch of these messages.

**Comment by azakus** [comment]
This message is printed in hydrolysis.
I assume that you are missing the `is` property in your Polymer 0.8 elements.

**Comment by MetaMemoryT** [comment]
I am trying to vulcanize 0.5 elements, would I have to use an older version of vulcanize?

**Comment by azakus** [comment]
Yes, vulcanize 1.x+ is only for Polymer 0.8+ elements.

**Comment by clintwood** [comment]
@azakus, I'm getting this on Polymer 1.0.x but could easily be a result of my own elements.
Is there a way to get better contextual feedback on where exactly this is occurring in the build/vulcanize process since `Ignoring duplicate element definition: undefined` doesn't really say much about where and what.
