### ISSUE TITLE
What's the role of loaders?

### ISSUE THREAD

**Issue by antonmoiseev** [Polymer/vulcanize#219]
I'm looking for a good way of pre-processing JS files when vulcanize inlines them into an HTML file. I've noticed there is a property called `loader` which is currently used only for hydrolysis. Unfortunately I haven't found any documentation on it. Could you explain what's the role of the `loader` property? Is it supposed to be used with custom loaders? Is it possible to configure multiple loaders? Can it potentially to be used for things such as transpiling, bundling JS modules (ES6/CommonJS modules)?

**Comment by azakus** [comment]
The loader property is passed through to hydrolysis to handle the file reading and dependency tree analyzing functions. Vulcanize exposes `loader` so that one could provide a custom hydrolysis loader plugin instead of the ones vulcanize builds: https://github.com/Polymer/vulcanize/blob/master/lib/vulcan.js#L32-L48

It could potentially be used for transpiling, as long as you follow the hydrolysis Loader API: https://github.com/Polymer/hydrolysis/blob/master/lib/loader/noop-resolver.js

**Comment by antonmoiseev** [comment]
I see, thank you for the clarification.
